import { Resend } from 'resend';
import { supabase } from '../db/client.js';

/**
 * Daily morning digest.
 *
 * Sent every day at the end of the pipeline run. Lists events first seen today,
 * grouped by city → date. Quiet days are silent — no email if nothing new.
 *
 * Recipients: DIGEST_TO_EMAIL (single recipient in v0; comma-separated list
 * support comes when there's more than one consumer of the digest).
 */

interface DigestArgs {
  runId: string;
  startedAt: string;
}

interface NewEventRow {
  artist_display: string;
  venue_display: string | null;
  city: string;
  date: string;
  end_date: string | null;
  type: 'concert' | 'festival';
  ticket_url: string | null;
}

export async function sendDigest({ runId, startedAt }: DigestArgs): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.DIGEST_TO_EMAIL;
  const from = process.env.DIGEST_FROM_EMAIL ?? 'digest@whiplash.local';

  if (!apiKey || !to) {
    console.warn(
      '[digest] RESEND_API_KEY or DIGEST_TO_EMAIL not set; skipping send',
    );
    return;
  }

  const newEvents = await loadEventsFirstSeenToday(startedAt);
  if (newEvents.length === 0) {
    console.info('[digest] no new events today; skipping send');
    return;
  }

  const resend = new Resend(apiKey);
  const html = renderDigest(newEvents, startedAt);
  const subject = `whiplash · ${newEvents.length} new event${newEvents.length === 1 ? '' : 's'} · ${dateLabel(startedAt)}`;

  await resend.emails.send({
    from,
    to,
    subject,
    html,
    headers: { 'X-Whiplash-Run-Id': runId },
  });
  console.info(`[digest] sent ${newEvents.length} new events to ${to}`);
}

async function loadEventsFirstSeenToday(startedAt: string): Promise<NewEventRow[]> {
  if (!supabase) return [];
  const today = startedAt.slice(0, 10); // YYYY-MM-DD

  const { data, error } = await supabase
    .from('events')
    .select(
      'artist_display, venue_display, city, date, end_date, type, ticket_url',
    )
    .gte('first_seen_at', `${today}T00:00:00Z`)
    .lt('first_seen_at', `${today}T23:59:59Z`)
    .order('city')
    .order('date');

  if (error) {
    console.error('[digest] supabase query failed', error);
    return [];
  }
  return (data ?? []) as NewEventRow[];
}

function renderDigest(events: NewEventRow[], startedAt: string): string {
  // Group by city → date
  const byCity: Record<string, NewEventRow[]> = {};
  for (const e of events) {
    (byCity[e.city] ??= []).push(e);
  }

  const sections = Object.entries(byCity)
    .map(([city, rows]) => {
      const items = rows
        .map((r) => {
          const dateStr = r.end_date && r.end_date !== r.date
            ? `${r.date} → ${r.end_date}`
            : r.date;
          const venue = r.venue_display ? ` · ${escape(r.venue_display)}` : '';
          const typeBadge = r.type === 'festival'
            ? ' <span style="background:#fef3c7;color:#92400e;padding:1px 6px;border-radius:3px;font-size:11px">FESTIVAL</span>'
            : '';
          const ticket = r.ticket_url
            ? ` · <a href="${escape(r.ticket_url)}" style="color:#1d4ed8">tickets</a>`
            : '';
          return `<li style="margin:6px 0;line-height:1.4">
            <strong>${escape(r.artist_display)}</strong>${typeBadge}<br>
            <span style="color:#6b7280;font-size:13px">${dateStr}${venue}${ticket}</span>
          </li>`;
        })
        .join('');
      return `<section style="margin:24px 0">
        <h2 style="font-size:14px;text-transform:uppercase;letter-spacing:.04em;color:#374151;margin:0 0 8px">${escape(cityLabel(city))}</h2>
        <ul style="list-style:none;padding:0;margin:0">${items}</ul>
      </section>`;
    })
    .join('');

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>whiplash digest</title></head>
<body style="font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#111">
  <header style="border-bottom:1px solid #e5e7eb;padding-bottom:12px;margin-bottom:8px">
    <div style="font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#6b7280">whiplash · ${dateLabel(startedAt)}</div>
    <h1 style="font-size:20px;margin:4px 0 0">${events.length} new event${events.length === 1 ? '' : 's'} today</h1>
  </header>
  ${sections}
  <footer style="margin-top:32px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af">
    Generated by whiplash · ${escape(startedAt)}
  </footer>
</body></html>`;
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function cityLabel(city: string): string {
  return city.charAt(0).toUpperCase() + city.slice(1);
}

function dateLabel(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-IN', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    timeZone: 'Asia/Kolkata',
  });
}
